image: ghcr.io/sprucecellodev125/custom-gitpod-image:latest

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - timonwong.shellcheck

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: true
